icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
# [theme.overrides]
# separator = "<span font='12'></span>"
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome6"
[icons.overrides]
volume_muted = "\uf026"

[[block]]
block = "backlight"
format = "$icon $brightness"

[[block]]
block = "sound"
format = "$icon $output_name{ $volume|} "
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "Speakers"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:3)"

[[block]]
block = "battery"
full_format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
charging_format = " $icon $percentage CHR"
not_charging_format = " $icon NOT CHR"
empty_format = " $icon EMPTY"
driver = "upower"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid}"
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %d/%m %R:%S')"

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
driver = "swaync"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

